/*
//------------------------------------------------------------------------------ 
// This code was generated by Amplication. 
// 
// Changes to this file will be lost if the code is regenerated. 
//
// There are other ways to to customize your code, see this doc to learn more
// https://docs.amplication.com/docs/how-to/custom-code
//
//------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import * as nestAccessControl from "nest-access-control";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import * as gqlUserRoles from "../../auth/gqlUserRoles.decorator";
import * as abacUtil from "../../auth/abac.util";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { DeleteSuportTicketArgs } from "./DeleteSuportTicketArgs";
import { SuportTicketFindManyArgs } from "./SuportTicketFindManyArgs";
import { SuportTicketFindUniqueArgs } from "./SuportTicketFindUniqueArgs";
import { SuportTicket } from "./SuportTicket";
import { SuportTicketService } from "../suportTicket.service";

@graphql.Resolver(() => SuportTicket)
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
export class SuportTicketResolverBase {
  constructor(
    protected readonly service: SuportTicketService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "SuportTicket",
    action: "read",
    possession: "any",
  })
  async _suportTicketsMeta(
    @graphql.Args() args: SuportTicketFindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @graphql.Query(() => [SuportTicket])
  @nestAccessControl.UseRoles({
    resource: "SuportTicket",
    action: "read",
    possession: "any",
  })
  async suportTickets(
    @graphql.Args() args: SuportTicketFindManyArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<SuportTicket[]> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "SuportTicket",
    });
    const results = await this.service.findMany(args);
    return results.map((result) => permission.filter(result));
  }

  @graphql.Query(() => SuportTicket, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "SuportTicket",
    action: "read",
    possession: "own",
  })
  async suportTicket(
    @graphql.Args() args: SuportTicketFindUniqueArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<SuportTicket | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "own",
      resource: "SuportTicket",
    });
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return permission.filter(result);
  }

  @graphql.Mutation(() => SuportTicket)
  @nestAccessControl.UseRoles({
    resource: "SuportTicket",
    action: "delete",
    possession: "any",
  })
  async deleteSuportTicket(
    @graphql.Args() args: DeleteSuportTicketArgs
  ): Promise<SuportTicket | null> {
    try {
      // @ts-ignore
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
