/*
//------------------------------------------------------------------------------ 
// This code was generated by Amplication. 
// 
// Changes to this file will be lost if the code is regenerated. 
//
// There are other ways to to customize your code, see this doc to learn more
// https://docs.amplication.com/docs/how-to/custom-code
//
//------------------------------------------------------------------------------
  */
import { ArgsType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { SuportTicketWhereInput } from "./SuportTicketWhereInput";
import { Type } from "class-transformer";
import { SuportTicketOrderByInput } from "./SuportTicketOrderByInput";

@ArgsType()
class SuportTicketFindManyArgs {
  @ApiProperty({
    required: false,
    type: () => SuportTicketWhereInput,
  })
  @Field(() => SuportTicketWhereInput, { nullable: true })
  @Type(() => SuportTicketWhereInput)
  where?: SuportTicketWhereInput;

  @ApiProperty({
    required: false,
    type: SuportTicketOrderByInput,
  })
  @Field(() => SuportTicketOrderByInput, { nullable: true })
  @Type(() => SuportTicketOrderByInput)
  orderBy?: SuportTicketOrderByInput;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @Field(() => Number, { nullable: true })
  @Type(() => Number)
  skip?: number;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @Field(() => Number, { nullable: true })
  @Type(() => Number)
  take?: number;
}

export { SuportTicketFindManyArgs };
